---
# This playbook contains common security settings that will be run on all nodes.

-   name: sshd - Use Only Approved Ciphers
    lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^Ciphers
        line: Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
        validate: sshd -t -f %s
    tags:
    - sshd_use_approved_ciphers

-   name: sshd - Disable SSH Root Login
    lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^PermitRootLogin
        line: PermitRootLogin no
        insertafter: (?i)^#?authentication
        validate: sshd -t -f %s
    tags:
    - sshd_disable_root_login

-   name: sshd - Print last log
    lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^PrintLastLog
        line: PrintLastLog yes
        validate: sshd -t -f %s
    tags:
    - sshd_print_last_log

-   name: Disable SSH Access via Empty Passwords
    lineinfile:
        create: true
        dest: /etc/ssh/sshd_config
        regexp: ^PermitEmptyPasswords
        line: PermitEmptyPasswords no
        validate: sshd -t -f %s
    tags:
    - sshd_disable_empty_passwords


